version: "3.8"

services:
  db:
    image: mysql:8.0.33
    restart: always
    env_file:
      - .env.db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - at

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: at_backend
    restart: always
    ports:
      - 4968:4968
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - at

networks:
  at:

volumes:
  db_data:
