version: "3"

services:
  db:
    image: mysql:8.0.33
    restart: always
    container_name: at_db
    env_file:
      - .env.db
    ports:
      - 3307:3306

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: at_backend
    volumes:
      - ./src:/app/src
    ports:
      - 4968:4968
    env_file:
      - .env
    depends_on:
      - db

volumes:
  src:
