version: "3"

services:
  db:
    image: mysql:8.0.33
    restart: always
    container_name: at_db
    env_file:
      - .env.db
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
